### ISSUE TITLE
Support negative indices

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/split-at#1]
Would be nice to be able to do `splitAt('unicorn', -4); //=> ['uni', 'corn']`.

A pull request would be super awesome :)

**Comment by kevva** [comment]
Wouldn't it be `['un', 'icorn']`, if it should mirror the positive ones?

**Comment by sindresorhus** [comment]
No, negative has to be 1 indexed as `slice`: `'unicorn'.slice(-4) //=> 'corn'`

**Comment by maxhallinan** [comment]
With a mix of positive and negative indices, there's a possibility that the returned array contains empty strings. For example: `splitAt('unicorn', [-4, 2]) //=> [ 'uni', '', 'corn' ]`. Is this acceptable? 

Edit: Nevermind; stupid question. I suspect the desired outcome of the above example is `splitAt('unicorn', [-4, 2]) //=> [ 'uni', 'co', 'rn' ]`.
