### ISSUE TITLE
[Question]: Why splitAt('unicorn', 1) is ['un', 'icorn'] instead of ['u', 'nicorn'] ?

### ISSUE THREAD

**Issue by rockmandash** [sindresorhus/split-at#4]
Why `splitAt('unicorn', 1)` is `['un', 'icorn']` instead of `['u', 'nicorn']` ?

`splitAt('unicorn', -1)` equals `['unicor', 'n']` is perfect.

But postive index is kinda weird, why design like this?

Rambda also has this API, but act different when given postive index.

https://ramdajs.com/docs/#splitAt

**Comment by sindresorhus** [comment]
> Why splitAt('unicorn', 1) is ['un', 'icorn'] instead of ['u', 'nicorn'] ?

This is how `String#split()` works too:

```js
'unicorn'.split('uni')[1];
//=> 'corn'
```

It splits **at** the given character, not before.

I guess both ways could make sense. I just chose to do it this way.

**Comment by rockmandash** [comment]
Thank you for explanation!!!!
